# Generated by Django 2.1.3 on 2019-01-29 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_auto_20190129_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='userID',
            new_name='usrID',
        ),
    ]
