# Generated by Django 2.1.3 on 2019-01-29 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_auto_20190129_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='usrID',
            new_name='userID',
        ),
    ]
