# Generated by Django 2.1.3 on 2019-01-31 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_remove_module_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
