# Generated by Django 2.1.2 on 2019-02-18 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0013_products_substrates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=200)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='modelName',
        ),
        migrations.RemoveField(
            model_name='module',
            name='moduleID',
        ),
        migrations.RemoveField(
            model_name='module',
            name='userID',
        ),
        migrations.AlterField(
            model_name='module',
            name='modelID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.Model'),
        ),
    ]
