# Generated by Django 2.1.2 on 2019-02-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0014_auto_20190218_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='enzymeAbbr',
            field=models.CharField(default='ENZYME', max_length=8),
        ),
        migrations.AddField(
            model_name='module',
            name='xCoor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='yCoor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='abbr',
            field=models.CharField(default='PROD', max_length=8),
        ),
        migrations.AddField(
            model_name='substrates',
            name='abbr',
            field=models.CharField(default='SUB', max_length=8),
        ),
    ]
