# Generated by Django 2.1.3 on 2019-03-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0016_auto_20190218_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='deltaG',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='module',
            name='deltaGNaughtPrime',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='module',
            name='enzWeight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='modelID',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='substrates',
            name='modelID',
            field=models.IntegerField(default=1),
        ),
    ]
