# Generated by Django 2.1.3 on 2019-03-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0017_auto_20190324_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='deltaG',
        ),
        migrations.RemoveField(
            model_name='module',
            name='deltaGNaughtPrime',
        ),
    ]
